network:
  businessType: wholesale
  locationType: local
server:
  port: 8081
spring:
  application:
    name: distributornetwork
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: tiger
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
