spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: tiger
  jpa:
    show-sql: true
    generate-ddl: false
  application:
    name: inventory-mgm

server:
  port: 8081
  
